#!/bin/bash

use_prelink="0" # this is secret feature; depends of prelink package; you can activate this if use use prelink; statements: 0/1 #

if [[ $(which sudo | grep -c sudo) = "1" ]]

	then

		sudo apt-get update

		sudo apt-get upgrade -y

		sudo apt-get dist-upgrade -y

		sudo apt-get install -y -f

		sudo apt-get check -y

		sudo apt-get autoremove -y

		sudo apt-get autoclean

		sudo apt-get clean

		sudo apt autoremove -y

		sudo apt autoclean

		sudo apt clean

	else

		apt-get update

		apt-get upgrade -y

		apt-get dist-upgrade -y

		apt-get install -y -f

		apt-get check -y

		apt-get autoremove -y

		apt-get autoclean

		apt-get clean

		apt autoremove -y

		apt autoclean

		apt clean

fi

if [[ $use_prelink = "1" ]]

	then

		if [[ $(which sudo | grep -c sudo) = "1" ]]

			then

				sudo prelink -a --all -f --force -m --conserve-memory -R --random -v --verbose

			else

				prelink -a --all -f --force -m --conserve-memory -R --random -v --verbose

		fi

	else

		sleep 0

fi
