#!/bin/bash

if [[ $(which sudo | grep -c sudo) = "1" ]]

	then

		sudo apt-get update

		sudo apt-get upgrade -y

		sudo apt-get dist-upgrade -y

		sudo apt-get install -y -f

		sudo apt-get check -y

		sudo apt-get autoremove -y

		sudo apt-get autoclean

		sudo apt-get clean

		sudo apt autoremove -y

		sudo apt autoclean

		sudo apt clean

	else

		apt-get update

		apt-get upgrade -y

		apt-get dist-upgrade -y

		apt-get install -y -f

		apt-get check -y

		apt-get autoremove -y

		apt-get autoclean

		apt-get clean

		apt autoremove -y

		apt autoclean

		apt clean

fi